name: 'NUnit HTML Report'
description: 'Generates an HTML report from NUnit XML test results'
inputs:
  inputXmlPath:
    description: 'XML input file path'
    required: true
  outputHtmlPath:
    description: 'HTML output file path'
    required: false
runs:
  using: "composite"
  steps:
    - run: python main.py
      shell: bash
branding:
  icon: 'file'
  color: 'green'